# Generated by Django 6.0.6 on 2026-06-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveDaemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=50)),
                ("host", models.CharField(default="0.0.0.0", max_length=50)),
                ("port", models.IntegerField(unique=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
